# Theme and Layout Helpers
# Purpose: Extract styling and component logic from app_ui.R for reuse and centralization

# Theme tokens - semantic color and spacing constants
theme_tokens <- function() {
  list(
    # Color palette
    color = list(
      background = "#f3efe7",
      background_shell = "#eee7dc",
      text_primary = "#1f2a30",
      text_muted = "#5b6870",
      border_light = "#d7dbdf",
      border_strong = "#b9c1c8",
      panel_bg = "#f6f7f8",
      panel_elevated = "#fbfaf7",
      panel_nested = "#fbfaf7",
      accent = "#163a59",
      accent_soft = "#e7eef5",
      accent_border = "#7aa6d8",
      success = "#e8f6ec",
      success_border = "#6db37c",
      success_text = "#14361d",
      error = "#fdeeee",
      error_border = "#d37b7b",
      error_text = "#5a1717",
      warning = "#fff4df",
      warning_border = "#d8a64b",
      warning_text = "#5d3b09",
      info = "#f6f7f8",
      info_border = "#d7dbdf",
      info_text = "#1f2a30",
      spinner = "#163a59"
    ),
    # Spacing (in pixels)
    spacing = list(
      xs = "4px",
      sm = "8px",
      md = "12px",
      lg = "16px",
      xl = "24px",
      xxl = "40px"
    ),
    # Typography
    typography = list(
      font_family = "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
      font_size_base = "14px",
      font_size_h1 = "24px",
      font_size_h3 = "18px",
      font_size_h4 = "16px",
      line_height = "1.5"
    ),
    # Borders and shadows
    border = list(
      radius = "8px",
      radius_sm = "5px",
      width = "1px",
      color = "#d7dbdf"
    ),
    # Layout
    layout = list(
      max_width = "1480px",
      content_padding = "20px 18px 40px"
    )
  )
}

# CSS variables injected into the document head
inject_theme_css_variables <- function() {
  tokens <- theme_tokens()
  css_vars <- paste(
    ":root {",
    sprintf("  --color-background: %s;", tokens$color$background),
    sprintf("  --color-background-shell: %s;", tokens$color$background_shell),
    sprintf("  --color-text-primary: %s;", tokens$color$text_primary),
    sprintf("  --color-text-muted: %s;", tokens$color$text_muted),
    sprintf("  --color-border-light: %s;", tokens$color$border_light),
    sprintf("  --color-border-strong: %s;", tokens$color$border_strong),
    sprintf("  --color-panel-bg: %s;", tokens$color$panel_bg),
    sprintf("  --color-panel-elevated: %s;", tokens$color$panel_elevated),
    sprintf("  --color-panel-nested: %s;", tokens$color$panel_nested),
    sprintf("  --color-accent: %s;", tokens$color$accent),
    sprintf("  --color-accent-soft: %s;", tokens$color$accent_soft),
    sprintf("  --color-accent-border: %s;", tokens$color$accent_border),
    sprintf("  --color-success: %s;", tokens$color$success),
    sprintf("  --color-success-border: %s;", tokens$color$success_border),
    sprintf("  --color-success-text: %s;", tokens$color$success_text),
    sprintf("  --color-error: %s;", tokens$color$error),
    sprintf("  --color-error-border: %s;", tokens$color$error_border),
    sprintf("  --color-error-text: %s;", tokens$color$error_text),
    sprintf("  --color-warning: %s;", tokens$color$warning),
    sprintf("  --color-warning-border: %s;", tokens$color$warning_border),
    sprintf("  --color-warning-text: %s;", tokens$color$warning_text),
    sprintf("  --color-info: %s;", tokens$color$info),
    sprintf("  --color-info-border: %s;", tokens$color$info_border),
    sprintf("  --color-info-text: %s;", tokens$color$info_text),
    sprintf("  --color-spinner: %s;", tokens$color$spinner),
    sprintf("  --spacing-xs: %s;", tokens$spacing$xs),
    sprintf("  --spacing-sm: %s;", tokens$spacing$sm),
    sprintf("  --spacing-md: %s;", tokens$spacing$md),
    sprintf("  --spacing-lg: %s;", tokens$spacing$lg),
    sprintf("  --spacing-xl: %s;", tokens$spacing$xl),
    sprintf("  --spacing-xxl: %s;", tokens$spacing$xxl),
    sprintf("  --layout-max-width: %s;", tokens$layout$max_width),
    sprintf("  --border-radius: %s;", tokens$border$radius),
    sprintf("  --border-radius-sm: %s;", tokens$border$radius_sm),
    "}",
    sep = "\n"
  )
  shiny::HTML(css_vars)
}

# Global app styles
get_global_styles <- function() {
  paste(
    "body {",
    "  background: var(--color-background);",
    "  color: var(--color-text-primary);",
    "  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;",
    "  font-size: 15px;",
    "  line-height: 1.5;",
    "  -webkit-font-smoothing: antialiased;",
    "}",
    "",
    "body, .container-fluid {",
    "  min-width: 0;",
    "}",
    "",
    ".app-shell {",
    "  width: 100%;",
    "  max-width: var(--layout-max-width);",
    "  margin: 0 auto;",
    "  padding: 16px 18px 40px;",
    "  box-sizing: border-box;",
    "  overflow-x: hidden;",
    "}",
    "",
    ".app-header {",
    "  display: flex;",
    "  align-items: center;",
    "  justify-content: space-between;",
    "  gap: 18px;",
    "  margin-bottom: 12px;",
    "  padding: 12px 14px;",
    "  border: 1px solid rgba(31, 42, 48, 0.10);",
    "  border-radius: 10px;",
    "  background: linear-gradient(180deg, rgba(251, 250, 247, 0.96), rgba(246, 247, 248, 0.94));",
    "}",
    "",
    ".app-header-brand {",
    "  display: flex;",
    "  align-items: center;",
    "  gap: 12px;",
    "  min-width: 0;",
    "}",
    "",
    ".app-header-icon {",
    "  width: 48px;",
    "  height: 48px;",
    "  flex-shrink: 0;",
    "}",
    "",
    ".app-header-text h1 {",
    "  margin: 0;",
    "  font-size: 24px;",
    "  font-weight: 600;",
    "  line-height: 1.1;",
    "}",
    "",
    ".app-header-text {",
    "  min-width: 0;",
    "}",
    "",
    ".app-lede {",
    "  margin: 0;",
    "  max-width: 82ch;",
    "  font-size: 13px;",
    "  color: var(--color-text-muted);",
    "  overflow-wrap: anywhere;",
    "}",
    "",
    ".app-header-meta {",
    "  display: flex;",
    "  gap: 8px;",
    "  flex-wrap: wrap;",
    "  justify-content: flex-end;",
    "  max-width: 100%;",
    "}",
    "",
    ".app-badge {",
    "  display: inline-flex;",
    "  align-items: center;",
    "  min-height: 28px;",
    "  padding: 4px 9px;",
    "  border: 1px solid rgba(22, 58, 89, 0.18);",
    "  border-radius: 999px;",
    "  background: rgba(231, 238, 245, 0.74);",
    "  color: var(--color-accent);",
    "  font-size: 11px;",
    "  font-weight: 700;",
    "  letter-spacing: 0.05em;",
    "  text-transform: uppercase;",
    "}",
    "",
    ".panel {",
    "  background: var(--color-panel-elevated);",
    "  border: 1px solid rgba(31, 42, 48, 0.11);",
    "  border-radius: var(--border-radius);",
    "  padding: 13px 14px;",
    "  margin-bottom: 12px;",
    "  box-shadow: 0 1px 0 rgba(31, 42, 48, 0.04);",
    "}",
    "",
    ".health-strip .status-success,",
    ".health-strip .status-error,",
    ".health-strip .status-info {",
    "  padding: 8px 10px;",
    "  margin-bottom: 12px;",
    "  overflow-wrap: anywhere;",
    "}",
    "",
    ".health-strip .status-success strong,",
    ".health-strip .status-error strong,",
    ".health-strip .status-info strong {",
    "  display: inline-block;",
    "  margin-right: 8px;",
    "  font-size: 13px;",
    "}",
    "",
    ".health-strip .status-success p,",
    ".health-strip .status-error p,",
    ".health-strip .status-info p {",
    "  display: inline;",
    "  margin: 0;",
    "  font-size: 12px;",
    "}",
    "",
    ".health-strip .status-success ul,",
    ".health-strip .status-error ul,",
    ".health-strip .status-info ul {",
    "  display: none;",
    "}",
    "",
    ".panel h3 {",
    "  margin: 0 0 10px 0;",
    "  font-size: 18px;",
    "  font-weight: 600;",
    "}",
    "",
    ".panel-title-row {",
    "  display: flex;",
    "  align-items: center;",
    "  gap: 8px;",
    "  margin: 0 0 8px 0;",
    "}",
    "",
    ".panel-title-row h3 {",
    "  margin: 0;",
    "}",
    "",
    ".panel-step-number {",
    "  display: inline-flex;",
    "  width: 22px;",
    "  height: 22px;",
    "  align-items: center;",
    "  justify-content: center;",
    "  flex-shrink: 0;",
    "  border-radius: 999px;",
    "  background: var(--color-accent);",
    "  color: var(--color-panel-bg);",
    "  font-size: 12px;",
    "  font-weight: 600;",
    "}",
    "",
    ".panel h4 {",
    "  margin: 8px 0 6px 0;",
    "  font-size: 12px;",
    "  font-weight: 700;",
    "  text-transform: uppercase;",
    "  letter-spacing: 0.5px;",
    "  color: var(--color-text-muted);",
    "}",
    "",
    ".workflow-steps {",
    "  display: grid;",
    "  grid-template-columns: repeat(4, minmax(0, 1fr));",
    "  gap: 6px;",
    "  margin-bottom: 12px;",
    "  padding: 6px;",
    "  border: 1px solid rgba(31, 42, 48, 0.10);",
    "  border-radius: 10px;",
    "  background: rgba(251, 250, 247, 0.62);",
    "}",
    "",
    ".workflow-step {",
    "  display: flex;",
    "  align-items: center;",
    "  gap: 8px;",
    "  min-height: 38px;",
    "  padding: 6px 9px;",
    "  border: 1px solid rgba(31, 42, 48, 0.09);",
    "  border-radius: 7px;",
    "  background: rgba(255, 255, 255, 0.46);",
    "}",
    "",
    ".workflow-step-number {",
    "  display: inline-flex;",
    "  width: 20px;",
    "  height: 20px;",
    "  align-items: center;",
    "  justify-content: center;",
    "  margin-right: 6px;",
    "  border-radius: 999px;",
    "  background: var(--color-accent);",
    "  color: var(--color-panel-bg);",
    "  font-size: 11px;",
    "  font-weight: 600;",
    "}",
    "",
    ".workflow-step-label {",
    "  font-size: 12px;",
    "  font-weight: 700;",
    "  text-transform: uppercase;",
    "  letter-spacing: 0.4px;",
    "}",
    "",
    ".panel-intro {",
    "  margin: 0 0 10px 0;",
    "  font-size: 13px;",
    "  line-height: 1.45;",
    "  color: var(--color-text-muted);",
    "}",
    "",
    ".section-note {",
    "  margin: 0 0 10px 0;",
    "  font-size: 12px;",
    "  opacity: 0.78;",
    "}",
    "",
    ".status-success {",
    "  padding: 10px 12px;",
    "  border-radius: var(--border-radius);",
    "  margin-bottom: 10px;",
    "  background: var(--color-success);",
    "  border: 1px solid var(--color-success-border);",
    "  color: var(--color-success-text);",
    "  border-left: 1px solid var(--color-success-border);",
    "}",
    "",
    ".status-error {",
    "  padding: 10px 12px;",
    "  border-radius: var(--border-radius);",
    "  margin-bottom: 10px;",
    "  background: var(--color-error);",
    "  border: 1px solid var(--color-error-border);",
    "  color: var(--color-error-text);",
    "  border-left: 1px solid var(--color-error-border);",
    "}",
    "",
    ".status-info {",
    "  padding: 10px 12px;",
    "  border-radius: var(--border-radius);",
    "  margin-bottom: 10px;",
    "  background: var(--color-info);",
    "  border: 1px solid var(--color-info-border);",
    "  color: var(--color-info-text);",
    "  border-left: 1px solid var(--color-info-border);",
    "}",
    "",
    ".status-compact {",
    "  padding: 9px 10px;",
    "  border-radius: var(--border-radius);",
    "  margin-bottom: 10px;",
    "}",
    "",
    ".status-compact p {",
    "  margin: 4px 0 0 0;",
    "}",
    "",
    ".compact-message-list {",
    "  margin: 6px 0 0 18px;",
    "  padding: 0;",
    "}",
    "",
    ".compact-message-list li {",
    "  margin-bottom: 2px;",
    "}",
    "",
    ".quality-metrics {",
    "  display: grid;",
    "  grid-template-columns: repeat(5, minmax(88px, 1fr));",
    "  gap: 8px;",
    "  margin-bottom: 10px;",
    "}",
    "",
    ".quality-metric {",
    "  padding: 8px 9px;",
    "  border: 1px solid rgba(31, 42, 48, 0.10);",
    "  border-radius: var(--border-radius);",
    "  background: rgba(255, 255, 255, 0.45);",
    "}",
    "",
    ".quality-metric-value {",
    "  display: block;",
    "  font-size: 17px;",
    "  font-weight: 600;",
    "  line-height: 1.2;",
    "}",
    "",
    ".quality-metric-label {",
    "  display: block;",
    "  margin-top: 3px;",
    "  font-size: 11px;",
    "  text-transform: uppercase;",
    "  letter-spacing: 0.35px;",
    "  opacity: 0.72;",
    "}",
    "",
    ".readiness-banner {",
    "  padding: 11px 12px;",
    "  border-radius: var(--border-radius);",
    "  margin-bottom: 8px;",
    "}",
    "",
    ".readiness-banner.ready {",
    "  background: var(--color-success);",
    "  border: 1px solid var(--color-success-border);",
    "  color: var(--color-success-text);",
    "}",
    "",
    ".readiness-banner.blocked {",
    "  background: var(--color-warning);",
    "  border: 1px solid var(--color-warning-border);",
    "  color: var(--color-warning-text);",
    "}",
    "",
    ".grouping-preview {",
    "  margin-bottom: 10px;",
    "}",
    "",
    ".grouping-preview h4,",
    ".plot-controls h4 {",
    "  margin-top: 0;",
    "}",
    "",
    ".plot-controls {",
    "  margin-bottom: 10px;",
    "  padding: 10px;",
    "  border: 1px solid rgba(31, 42, 48, 0.08);",
    "  border-radius: var(--border-radius);",
    "  background: rgba(255, 255, 255, 0.35);",
    "}",
    "",
    ".resizable-plot-frame {",
    "  position: relative;",
    "  width: 100%;",
    "  height: 420px;",
    "  min-height: 300px;",
    "  max-height: 760px;",
    "  resize: vertical;",
    "  overflow: hidden;",
    "  border: 1px solid rgba(31, 42, 48, 0.12);",
    "  border-radius: var(--border-radius);",
    "  background: var(--color-panel-nested);",
    "}",
    "",
    ".resizable-plot-frame .shiny-plot-output {",
    "  width: 100% !important;",
    "  height: 100% !important;",
    "}",
    "",
    ".plot-resize-grip {",
    "  position: absolute;",
    "  right: 2px;",
    "  bottom: 2px;",
    "  width: 18px;",
    "  height: 18px;",
    "  cursor: ns-resize;",
    "  border-right: 2px solid rgba(31, 42, 48, 0.35);",
    "  border-bottom: 2px solid rgba(31, 42, 48, 0.35);",
    "  background: linear-gradient(135deg, transparent 0 45%, rgba(31, 42, 48, 0.18) 45% 55%, transparent 55% 100%);",
    "}",
    "",
    ".stack-tight > * + * {",
    "  margin-top: 8px;",
    "}",
    "",
    ".compact-field-grid {",
    "  display: grid;",
    "  grid-template-columns: repeat(2, minmax(0, 1fr));",
    "  gap: 8px 12px;",
    "  align-items: start;",
    "}",
    "",
    ".compact-field-grid > .form-group {",
    "  margin-bottom: 0;",
    "}",
    "",
    ".compact-field-grid .shiny-input-container {",
    "  width: 100%;",
    "  margin-bottom: 0;",
    "}",
    "",
    ".workspace-top-row,",
    ".workspace-results-row {",
    "  margin-left: -7px;",
    "  margin-right: -7px;",
    "}",
    "",
    ".workspace-top-row > [class*='col-'],",
    ".workspace-results-row > [class*='col-'] {",
    "  padding-left: 7px;",
    "  padding-right: 7px;",
    "}",
    "",
    ".workspace-side-column .panel {",
    "  margin-bottom: 12px;",
    "}",
    "",
    ".bench-workspace {",
    "  display: grid;",
    "  grid-template-columns: minmax(0, 1fr) minmax(330px, 0.44fr);",
    "  gap: 12px;",
    "  align-items: start;",
    "}",
    "",
    ".bench-config-stack,",
    ".bench-run-rail {",
    "  min-width: 0;",
    "}",
    "",
    ".bench-results-row {",
    "  margin-top: 0;",
    "}",
    "",
    ".run-panel {",
    "  position: sticky;",
    "  top: 12px;",
    "  z-index: 10;",
    "}",
    "",
    ".sticky-run-shell {",
    "  margin-bottom: 10px;",
    "  padding: 12px;",
    "  border: 1px solid rgba(22, 58, 89, 0.14);",
    "  border-radius: var(--border-radius);",
    "  background: linear-gradient(180deg, rgba(246, 247, 248, 0.98), rgba(243, 239, 231, 0.96));",
    "  box-shadow: 0 8px 20px rgba(31, 42, 48, 0.08);",
    "}",
    "",
    ".run-header-row {",
    "  display: flex;",
    "  align-items: center;",
    "  justify-content: space-between;",
    "  gap: 12px;",
    "  margin-bottom: 10px;",
    "}",
    "",
    ".run-header-row h4 {",
    "  margin: 0;",
    "}",
    "",
    ".run-header-row .shiny-html-output,",
    ".run-header-row .btn {",
    "  margin-bottom: 0;",
    "}",
    "",
    ".results-workspace {",
    "  margin-top: 10px;",
    "  padding: 10px;",
    "  border: 1px solid rgba(31, 42, 48, 0.08);",
    "  border-radius: var(--border-radius);",
    "  background: rgba(255, 255, 255, 0.35);",
    "}",
    "",
    ".results-balance-grid {",
    "  display: grid;",
    "  grid-template-columns: minmax(320px, 0.95fr) minmax(440px, 1.25fr);",
    "  gap: 12px;",
    "  align-items: start;",
    "}",
    "",
    ".result-stack {",
    "  display: grid;",
    "  gap: 10px;",
    "  min-width: 0;",
    "}",
    "",
    ".result-block {",
    "  padding: 10px;",
    "  border: 1px solid rgba(31, 42, 48, 0.08);",
    "  border-radius: var(--border-radius);",
    "  background: rgba(255, 255, 255, 0.58);",
    "  min-width: 0;",
    "}",
    "",
    ".result-block h4 {",
    "  margin-top: 0;",
    "}",
    "",
    ".results-workspace .nav-tabs {",
    "  margin-bottom: 8px;",
    "}",
    "",
    ".results-workspace .tab-content {",
    "  min-height: 220px;",
    "}",
    "",
    ".panel table {",
    "  margin-bottom: 0;",
    "}",
    "",
    ".panel .form-group {",
    "  margin-bottom: 10px;",
    "}",
    "",
    ".panel .radio {",
    "  margin-top: 4px;",
    "  margin-bottom: 4px;",
    "}",
    "",
    ".panel .help-block {",
    "  margin-bottom: 0;",
    "}",
    "",
    ".form-group label,",
    ".control-label {",
    "  color: var(--color-text-primary);",
    "  font-size: 12px;",
    "  font-weight: 700;",
    "  letter-spacing: 0.02em;",
    "}",
    "",
    ".form-control,",
    "select.form-control,",
    "textarea.form-control {",
    "  border-color: var(--color-border-strong);",
    "  border-radius: var(--border-radius-sm);",
    "  background: var(--color-panel-nested);",
    "  color: var(--color-text-primary);",
    "  box-shadow: none;",
    "}",
    "",
    ".form-control:focus,",
    "select.form-control:focus,",
    "textarea.form-control:focus {",
    "  border-color: var(--color-accent);",
    "  box-shadow: 0 0 0 2px rgba(22, 58, 89, 0.14);",
    "}",
    "",
    ".btn {",
    "  border-radius: var(--border-radius-sm);",
    "  font-weight: 700;",
    "}",
    "",
    ".btn-primary,",
    ".btn-primary:focus {",
    "  background: var(--color-accent);",
    "  border-color: var(--color-accent);",
    "  color: var(--color-panel-bg);",
    "}",
    "",
    ".btn-primary:hover {",
    "  background: #0f2e47;",
    "  border-color: #0f2e47;",
    "}",
    "",
    ".btn-default {",
    "  background: var(--color-panel-nested);",
    "  border-color: var(--color-border-strong);",
    "  color: var(--color-text-primary);",
    "}",
    "",
    ".btn-default:hover {",
    "  background: var(--color-accent-soft);",
    "  border-color: var(--color-accent-border);",
    "  color: var(--color-accent);",
    "}",
    "",
    ".btn:focus-visible,",
    "summary:focus-visible,",
    ".plot-resize-grip:focus-visible {",
    "  outline: 2px solid var(--color-accent);",
    "  outline-offset: 2px;",
    "}",
    "",
    ".spinner {",
    "  display: inline-block;",
    "  width: 16px;",
    "  height: 16px;",
    "  border: 2px solid rgba(22, 58, 89, 0.2);",
    "  border-top-color: var(--color-spinner);",
    "  border-radius: 50%;",
    "  animation: spin 1.2s linear infinite;",
    "  vertical-align: middle;",
    "  margin-left: var(--spacing-sm);",
    "}",
    "",
    "@keyframes spin {",
    "  to { transform: rotate(360deg); }",
    "}",
    "",
    ".section-advanced {",
    "  margin-top: 12px;",
    "  padding-top: 12px;",
    "  border-top: 1px solid var(--color-border-light);",
    "}",
    "",
    ".section-advanced summary {",
    "  cursor: pointer;",
    "  font-weight: 600;",
    "  color: var(--color-text-primary);",
    "  padding: 6px 0;",
    "  user-select: none;",
    "}",
    "",
    ".section-advanced summary:hover {",
    "  opacity: 0.8;",
    "}",
    "",
    ".section-advanced-content {",
    "  margin-top: 8px;",
    "  padding: 10px 12px;",
    "  background: rgba(31, 42, 48, 0.02);",
    "  border-radius: var(--border-radius);",
    "  border: 1px solid rgba(31, 42, 48, 0.08);",
    "}",
    "",
    ".section-grouped {",
    "  margin: 12px 0;",
    "  padding: 10px 12px;",
    "  background: rgba(109, 179, 124, 0.05);",
    "  border: 1px solid rgba(109, 179, 124, 0.3);",
    "  border-radius: var(--border-radius);",
    "}",
    "",
    ".section-grouped h5 {",
    "  margin: 0 0 var(--spacing-sm) 0;",
    "  font-size: 14px;",
    "  font-weight: 600;",
    "  color: #14361d;",
    "}",
    "",
    "@media (max-width: 1199px) {",
    "  .bench-workspace,",
    "  .results-balance-grid {",
    "    grid-template-columns: 1fr;",
    "  }",
    "  .compact-field-grid {",
    "    grid-template-columns: 1fr;",
    "  }",
    "  .quality-metrics,",
    "  .workflow-steps {",
    "    grid-template-columns: repeat(2, minmax(0, 1fr));",
    "  }",
    "  .sticky-run-shell {",
    "    position: static;",
    "  }",
    "  .run-panel {",
    "    position: static;",
    "  }",
    "}",
    "",
    "@media (max-width: 768px) {",
    "  .app-shell {",
    "    padding: var(--spacing-lg) var(--spacing-sm) var(--spacing-lg);",
    "  }",
    "  .app-header {",
    "    flex-direction: column;",
    "    align-items: flex-start;",
    "  }",
    "  .app-header-meta {",
    "    justify-content: flex-start;",
    "    width: 100%;",
    "  }",
    "  .app-badge {",
    "    font-size: 10px;",
    "    min-height: 26px;",
    "    padding: 3px 8px;",
    "  }",
    "  .health-strip .status-success p,",
    "  .health-strip .status-error p,",
    "  .health-strip .status-info p {",
    "    display: block;",
    "    margin-top: 4px;",
    "  }",
    "  .app-header-icon {",
    "    width: 48px;",
    "    height: 48px;",
    "  }",
    "  .compact-field-grid {",
    "    grid-template-columns: 1fr;",
    "  }",
    "  .quality-metrics,",
    "  .workflow-steps {",
    "    grid-template-columns: 1fr;",
    "  }",
    "  .run-header-row {",
    "    flex-direction: column;",
    "    align-items: stretch;",
    "  }",
    "  .results-balance-grid {",
    "    grid-template-columns: minmax(0, 1fr);",
    "  }",
    "  .resizable-plot-frame {",
    "    height: 340px;",
    "  }",
    "}",
    sep = "\n"
  )
}

# Panel builder with consistent styling
build_panel <- function(title, ..., id = NULL, step_number = NULL) {
  title_content <- if (!is.null(title)) {
    shiny::tags$div(
      class = "panel-title-row",
      if (!is.null(step_number)) {
        shiny::span(class = "panel-step-number", step_number)
      },
      shiny::tags$h3(title)
    )
  }

  shiny::wellPanel(
    class = "panel",
    title_content,
    ...
  )
}

# Status card builders
build_status_card <- function(type = "info", title = NULL, message = NULL, details = NULL) {
  class_name <- sprintf("status-%s", type)
  
  shiny::tags$div(
    class = class_name,
    if (!is.null(title)) shiny::tags$strong(title),
    if (!is.null(message)) shiny::tags$p(message),
    if (!is.null(details)) shiny::tags$p(sprintf("Details: %s", details))
  )
}

# Responsive grid helpers
grid_row <- function(...) {
  shiny::fluidRow(...)
}

grid_col_6 <- function(...) {
  shiny::column(6, ...)
}

# Branding header with icon
build_branded_header <- function(title, lede, icon_path = NULL) {
  header_content <- shiny::tags$div(
    class = "app-header",
    shiny::tags$div(
      class = "app-header-brand",
      if (!is.null(icon_path)) {
        shiny::tags$img(
          class = "app-header-icon",
          src = icon_path,
          alt = "refineR Logo"
        )
      },
      shiny::tags$div(
        class = "app-header-text",
        shiny::tags$h1(title),
        shiny::tags$p(class = "app-lede", lede)
      )
    ),
    shiny::tags$div(
      class = "app-header-meta",
      shiny::span(class = "app-badge", "Local Shiny"),
      shiny::span(class = "app-badge", "refineR wrapper"),
      shiny::span(class = "app-badge", "No hosted data")
    )
  )
  
  header_content
}

# Collapsible section for advanced or secondary controls
build_collapsible_section <- function(title, ..., open = FALSE) {
  shiny::tags$details(
    class = "section-advanced",
    open = if (open) "open" else NULL,
    shiny::tags$summary(title),
    shiny::tags$div(
      class = "section-advanced-content",
      ...
    )
  )
}

# Grouped workflow section (highlighted background)
build_grouped_section <- function(title, ...) {
  shiny::tags$fieldset(
    class = "section-grouped",
    shiny::tags$h5(title),
    ...
  )
}

# Export all helpers for use in app_ui.R
export_theme_helpers <- function() {
  list(
    theme_tokens = theme_tokens,
    inject_theme_css_variables = inject_theme_css_variables,
    get_global_styles = get_global_styles,
    build_panel = build_panel,
    build_status_card = build_status_card,
    grid_row = grid_row,
    grid_col_6 = grid_col_6,
    build_branded_header = build_branded_header,
    build_collapsible_section = build_collapsible_section,
    build_grouped_section = build_grouped_section
  )
}
